# Generated by Django 4.1.4 on 2022-12-12 20:03

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000, verbose_name='Название')),
                ('description', models.CharField(max_length=1000, verbose_name='Описание')),
                ('category', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='product_category', to='shop_cite.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000, verbose_name='Название')),
                ('address', models.CharField(max_length=1000, verbose_name='Адрес')),
            ],
            options={
                'verbose_name': 'Магазин',
                'verbose_name_plural': 'Магазины',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('З', 'Золото'), ('C', 'Серебро'), ('Б', 'Бронза')], max_length=10, verbose_name='Статус')),
                ('payment_method', models.CharField(choices=[('Б', 'Безнал'), ('К', 'Карта'), ('Н', 'Наличные')], max_length=10, verbose_name='Тип оплаты')),
                ('user', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='userprofile_user', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Профиль пользователя',
                'verbose_name_plural': 'Профили пользователей',
            },
        ),
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(default=0.0, verbose_name='Цена')),
                ('amount', models.IntegerField(default=0, verbose_name='Количество')),
                ('product', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='storage_product', to='shop_cite.product', verbose_name='Товар')),
                ('store', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='storage_store', to='shop_cite.store', verbose_name='Магазин')),
            ],
            options={
                'verbose_name': 'Склад',
                'verbose_name_plural': 'Склады',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=0, verbose_name='Оценка')),
                ('description', models.CharField(max_length=1000, verbose_name='Текст отзыва')),
                ('product', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='review_product', to='shop_cite.product', verbose_name='Товар')),
                ('store', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='review_store', to='shop_cite.store', verbose_name='Магазин')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='review_user', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(default=0.0, verbose_name='Цена')),
                ('amount', models.IntegerField(default=0, verbose_name='Количество')),
                ('purchase_date', models.DateTimeField(default=datetime.datetime.now, verbose_name='Дата покупки')),
                ('purchase_number', models.BigIntegerField(default=0, verbose_name='Номер заказа')),
                ('product', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='purchase_product', to='shop_cite.product', verbose_name='Товар')),
                ('store', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='purchase_store', to='shop_cite.store', verbose_name='Магазин')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='purchase_user', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Покупка',
                'verbose_name_plural': 'Покупки',
            },
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=1000, verbose_name='Адрес')),
                ('store', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='delivery_store', to='shop_cite.store', verbose_name='Магазин')),
            ],
            options={
                'verbose_name': 'Адрес доставки магазина',
                'verbose_name_plural': 'Адреса доставки магазинов',
            },
        ),
        migrations.CreateModel(
            name='Basket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(default=0.0, verbose_name='Цена')),
                ('amount', models.IntegerField(default=0, verbose_name='Количество')),
                ('product', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='basket_product', to='shop_cite.product', verbose_name='Товар')),
                ('store', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='basket_store', to='shop_cite.store', verbose_name='Магазин')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='basket_user', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Корзина',
                'verbose_name_plural': 'Корзины',
            },
        ),
    ]
