# Generated by Django 4.1.4 on 2022-12-17 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop_cite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image_src',
            field=models.CharField(default='', max_length=1000, verbose_name='Иконка'),
        ),
        migrations.AddField(
            model_name='category',
            name='parent_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='shop_cite.category'),
        ),
        migrations.AddField(
            model_name='category',
            name='short_image_name',
            field=models.CharField(default='', max_length=1000, verbose_name='Короткое название'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(default='', max_length=1000, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='payment_method',
            field=models.CharField(choices=[('Б', 'Безнал'), ('К', 'Карта'), ('Н', 'Наличные'), ('-', 'Не указано')], max_length=10, verbose_name='Тип оплаты'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='status',
            field=models.CharField(choices=[('А', 'Администратор'), ('П', 'Покупатель'), ('Н', 'Незарегистрированный пользователь')], max_length=10, verbose_name='Статус'),
        ),
    ]
