# Generated by Django 4.1.4 on 2022-12-28 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_cite', '0003_alter_basket_product_alter_basket_store_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='has_subcategories',
            field=models.BooleanField(default=False, verbose_name='Есть подкатегории'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='payment_method',
            field=models.CharField(choices=[('Б', 'Безнал'), ('К', 'Карта'), ('Н', 'Наличные'), ('-', 'Не указано')], default='-', max_length=10, verbose_name='Тип оплаты'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='status',
            field=models.CharField(choices=[('А', 'Администратор'), ('П', 'Покупатель'), ('Н', 'Незарегистрированный пользователь')], default='П', max_length=10, verbose_name='Статус'),
        ),
    ]
