# Generated by Django 4.1.4 on 2022-12-29 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop_cite', '0004_category_has_subcategories_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='big_image_src',
            field=models.CharField(default='', max_length=1000, verbose_name='Большая иконка'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(default='', max_length=1000, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='category',
            name='parent_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop_cite.category', verbose_name='Родительская категория'),
        ),
    ]
