# Generated by Django 4.1.4 on 2023-01-05 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_cite', '0006_remove_storage_price_product_main_image_src_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='add1_image_src',
            field=models.CharField(default='', max_length=1000, verbose_name='Доп1'),
        ),
        migrations.AddField(
            model_name='product',
            name='add2_image_src',
            field=models.CharField(default='', max_length=1000, verbose_name='Доп2'),
        ),
        migrations.DeleteModel(
            name='AdditionalProductImages',
        ),
    ]
