# Generated by Django 4.1.4 on 2023-01-05 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_cite', '0007_product_add1_image_src_product_add2_image_src_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='add3_image_src',
            field=models.CharField(default='', max_length=1000, verbose_name='Доп3'),
        ),
    ]
