# Generated by Django 4.1.4 on 2023-01-05 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop_cite', '0008_product_add3_image_src'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCharacteristics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(max_length=1000, verbose_name='Группа')),
                ('name', models.CharField(max_length=1000, verbose_name='Название')),
                ('value', models.CharField(max_length=1000, verbose_name='Значение')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_characteristic', to='shop_cite.product', verbose_name='Товар')),
            ],
        ),
    ]
