# Generated by Django 4.1.4 on 2023-01-09 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_cite', '0009_productcharacteristics'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productcharacteristics',
            options={'verbose_name': 'Характеристика', 'verbose_name_plural': 'Характеристики'},
        ),
        migrations.AddField(
            model_name='userprofile',
            name='address',
            field=models.CharField(default='', max_length=1000, verbose_name='ФИО'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='delivery_type',
            field=models.CharField(choices=[('О', 'Обычная'), ('Э', 'Экспресс')], default='О', max_length=10, verbose_name='Тип доставки'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='full_name',
            field=models.CharField(default='', max_length=1000, verbose_name='ФИО'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(default='+70000000000', max_length=12, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='payment_method',
            field=models.CharField(choices=[('К', 'Онлайн карта'), ('Н', 'Наличные при получении')], default='Н', max_length=100, verbose_name='Тип оплаты'),
        ),
    ]
