# Generated by Django 4.1.4 on 2023-01-12 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_cite', '0010_alter_productcharacteristics_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='delivery_state',
            field=models.CharField(choices=[('Д', 'Доставляется'), ('Г', 'Готов к выдаче'), ('В', 'Выдан покупателю')], default='Д', max_length=1, verbose_name='Статус доставки'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='delivery_type',
            field=models.CharField(choices=[('О', 'Обычная'), ('Э', 'Экспресс')], default='О', max_length=1, verbose_name='Тип доставки'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='payment_method',
            field=models.CharField(choices=[('К', 'Онлайн картой'), ('Н', 'Наличными при получении')], default='Н', max_length=1, verbose_name='Тип оплаты'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='payment_state',
            field=models.CharField(choices=[('Н', 'Не оплачен'), ('О', 'Оплачен')], default='Н', max_length=1, verbose_name='Статус оплаты'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='delivery_type',
            field=models.CharField(choices=[('О', 'Обычная'), ('Э', 'Экспресс')], default='О', max_length=1, verbose_name='Тип доставки'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='payment_method',
            field=models.CharField(choices=[('К', 'Онлайн картой'), ('Н', 'Наличными при получении')], default='Н', max_length=1, verbose_name='Тип оплаты'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='status',
            field=models.CharField(choices=[('А', 'Администратор'), ('П', 'Покупатель'), ('Н', 'Незарегистрированный пользователь')], default='П', max_length=1, verbose_name='Статус'),
        ),
    ]
