# Generated by Django 4.1.4 on 2023-01-12 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_cite', '0011_purchase_delivery_state_purchase_delivery_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='town',
            field=models.CharField(default='', max_length=1000, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='address',
            field=models.CharField(default='', max_length=1000, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(default='+70000000000', max_length=12, verbose_name='Телефон'),
        ),
    ]
