# Generated by Django 4.1.4 on 2023-01-12 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop_cite', '0012_userprofile_town_alter_userprofile_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='price',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='product',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='purchase_number',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='store',
        ),
        migrations.AlterField(
            model_name='purchase',
            name='delivery_state',
            field=models.CharField(choices=[('С', 'Собирается'), ('Д', 'Доставляется'), ('Г', 'Готов к выдаче'), ('В', 'Выдан покупателю')], default='Д', max_length=1, verbose_name='Статус доставки'),
        ),
        migrations.CreateModel(
            name='ProductPurchased',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(default=0.0, verbose_name='Цена')),
                ('amount', models.IntegerField(default=0, verbose_name='Количество')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_product', to='shop_cite.product', verbose_name='Товар')),
                ('purchase', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_purchase', to='shop_cite.purchase', verbose_name='Заказ')),
                ('store', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_store', to='shop_cite.store', verbose_name='Магазин')),
            ],
            options={
                'verbose_name': 'Заказанный товар',
                'verbose_name_plural': 'Заказанные товары',
            },
        ),
    ]
