# Generated by Django 4.1.4 on 2023-01-14 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_cite', '0015_alter_purchase_options_remove_purchase_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='total_sum',
            field=models.FloatField(default=0, verbose_name='Сумма заказа'),
        ),
    ]
