# Generated by Django 4.1.4 on 2023-01-26 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_cite', '0017_review_update_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='images/profiles/'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='delivery_state',
            field=models.CharField(choices=[('С', 'Собирается'), ('Д', 'Доставляется'), ('Г', 'Готов к выдаче'), ('В', 'Завершён')], default='С', max_length=1, verbose_name='Статус доставки'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='payment_method',
            field=models.CharField(choices=[('К', 'Онлайн картой'), ('Н', 'Онлайн со случайного счёта')], default='Н', max_length=1, verbose_name='Тип оплаты'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='payment_state',
            field=models.CharField(choices=[('Н', 'Ожидается оплата'), ('О', 'Оплачен')], default='Н', max_length=1, verbose_name='Статус оплаты'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='payment_method',
            field=models.CharField(choices=[('К', 'Онлайн картой'), ('Н', 'Онлайн со случайного счёта')], default='Н', max_length=1, verbose_name='Тип оплаты'),
        ),
    ]
